### ISSUE TITLE
Notebook samples do not work

### ISSUE THREAD

**Issue by Mvenkateswaramma** [Azure-Samples/azureai-samples#77] opened 2024-03-29 04:38 UTC
### Operating System

Windows

### Version Information

Operating System
Windows

Version Information
Python Version: 3.12.2

I am following the notebook sample verbatim found [HERE](https://github.com/Azure-Samples/azureai-samples/blob/main/scenarios/Assistants/assistants-api-in-a-box/notebooks/assistant-failed_banks.ipynb). It does not work.

The cell where you prep the assistand with the file_ids throws:
NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### Steps to reproduce

Just try to run the sample.

### Expected behavior

It should be able to answer the questions using process_message

### Actual behavior

Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by sjkp** [comment] 2024-04-01 14:28
Are you using a gpt4 1101 deployment? I got this error when using GPT3.5.

**Comment by Mvenkateswaramma** [comment] 2024-04-01 17:01
> Are you using a gpt4 1101 deployment? I got this error when using GPT3.5.

Hi I am using Model name: gpt-4
Model version: 1106-Preview

**Comment by kdestin** [comment] 2024-04-01 18:42
Duplicate of #58

**Closed by kdestin** 2024-04-01 18:42 UTC
Labels: bug

**Comment by thomassantosh** [comment] 2024-05-07 01:47
I was running into the same issue. However, from this [documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant#api-version) it's important to ensure you use the right API version (at the time of reference `2024-02-15-preview`). I was using the wrong API version and getting the error code listed above.
