### ISSUE TITLE
Sample Assistants - Jupyter notebooks

### ISSUE THREAD

**Issue by arashaga** [Azure-Samples/azureai-samples#61] opened 2024-02-26 15:57 UTC
### Operating System

Windows

### Version Information

Sample Assistants - Jupyter notebooks that are listed on the Assistants API-in-a-Box readme file are not available ( the links are broken)

Topic	Description
[Assistant-01: Foundational Concepts](https://github.com/Azure-Samples/azureai-samples/blob/main/scenarios/Assistants/assistants-api-in-a-box/notebooks/assistant-01-math_tutor.ipynb)	Showcases the foundational concepts of Assistants such as Threads, Messages, Runs, Tools, and lifecycle management.
[Assistant-02: Helper](https://github.com/Azure-Samples/azureai-samples/blob/main/scenarios/Assistants/assistants-api-in-a-box/notebooks/assistant-02-financial_reporting.ipynb)	The aihelper.py file serves as a helper library that extracts repetitive code, such as handling lifetime events. It keeps track of instantiated Assistants, Files, and Threads, and can dispose of them when they are no longer needed. aihelper.py also provides a delegate interface to pass Assistant functions. While it is not mandatory to use aihelper.py in your code, this Assistant and the others depend on it.
[Assistant-03: Financial Summary Assistant](https://github.com/Azure-Samples/azureai-samples/blob/main/scenarios/Assistants/assistants-api-in-a-box/notebooks/assistant-03-portfolio_reporting.ipynb)	Using Function calling, this Assistant can summarize a financial news article, extract the ticker symbols from the article, and provide a summary of the article and the latest (simulated) stock prices.
[Assistant-04: Portpolio Reporting Assistant](https://github.com/Azure-Samples/azureai-samples/blob/main/scenarios/Assistants/assistants-api-in-a-box/notebooks/assistant-04-sales_assistant.ipynb)	Using Assistant tools Code Interpreter and Function calling, this bot can get a CSV portfolio file, calculate the latest portfolio value based on the latest stock prices, point out the best and the worst investment, and email a report to a client.
Prerequisites

### Steps to reproduce

go to the  Assistants API-in-a-Box readme page

### Expected behavior

the sample notebooks should be there by clicking on the links

### Actual behavior

the links mentioned above are not avaiable.

**Comment by kdestin** [comment] 2024-02-27 20:46
Duplicate of #55

**Closed by kdestin** 2024-02-27 20:46 UTC
Labels: bug
